version = [1, 0]
frame_counter = true

[window]
x = 0
y = 0
width = 1024
height = 768

[resolution]
width = 640 
height = 480 

[shader]
vs_args = []
ps_args = []

[appearance]
clear_color = [0.0, 0.0, 0.3]
font = "Yu Gothic UI"
font_size = 12.0
text_color = [1.0, 1.0, 1.0, 1.0]
background_color = [0.0, 0.0, 0.0, 0.7]