version = [1, 0]
frame_counter = true
auto_play = true

[window]
x = 0
y = 0
width = 1024
height = 768
maximized = false

[resolution]
width = 640 
height = 480 

[shader]
vs_args = []
ps_args = []

[appearance]
clear_color = [0.1, 0.1, 0.1]
font = "Yu Gothic UI"
font_size = 12.0
text_color = [1.0, 1.0, 1.0, 1.0]
background_color = [0.0, 0.0, 0.0, 0.7]
error_label_color = [0.9, 0.0, 0.0, 1.0]
warn_label_color = [0.9, 0.9, 0.0, 1.0]
info_label_color = [0.0, 0.9, 0.0, 1.0]
under_line_color = [0.8, 0.8, 0.0, 1.0]

[appearance.scroll_bar]
width = 15.0
bg_color = [0.1, 0.1, 0.1, 0.7]
thumb_color = [0.7, 0.7, 0.7, 0.7]
thumb_hover_color = [0.7, 0.7, 0.7, 0.9]
thumb_moving_color = [0.8, 0.8, 0.8, 1.0]
